name: aksan_mobile
description: "Aksan Mobile Uygulaması"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

flutter_launcher_icons:
  image_path: "assets/images/Kalde_logo.png"
  adaptive_icon_foreground: "assets/images/Kalde_logo.png"
  adaptive_icon_background: "#ffffff"
  android: "ic_launcher"
  ios: "ic_launcher"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/Kalde_logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/Kalde_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/Kalde_logo.png"
   
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.2
  webview_flutter: ^4.4.4
  webview_flutter_android: ^3.14.0
  webview_flutter_wkwebview: ^3.11.0
  flutter_launcher_icons: ^0.13.1
  quiver: ^3.2.1
  url_launcher: ^6.2.4
  adaptive_navigation: ^0.0.10
  path_to_regexp: ^0.4.0
  collection: ^1.18.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
